const projectData = {
    "story_link": {
        "title": "storyboards",
        "projects": [
            {
                "title": "Big Cat Little Cat",
                "type": "slideshow",
                "icon": "images/BC_LC_card.jpg",
                "imageSequence": [
"images/BCLC/BC_LC_test-001.jpg",
"images/BCLC/BC_LC_test-002.jpg",
"images/BCLC/BC_LC_test-003.jpg",
"images/BCLC/BC_LC_test-004.jpg",
"images/BCLC/BC_LC_test-005.jpg",
"images/BCLC/BC_LC_test-006.jpg",
"images/BCLC/BC_LC_test-007.jpg",
"images/BCLC/BC_LC_test-008.jpg",
"images/BCLC/BC_LC_test-009.jpg",
"images/BCLC/BC_LC_test-010.jpg",
"images/BCLC/BC_LC_test-011.jpg",
"images/BCLC/BC_LC_test-012.jpg",
"images/BCLC/BC_LC_test-013.jpg",
"images/BCLC/BC_LC_test-016.jpg",
"images/BCLC/BC_LC_test-017.jpg",
"images/BCLC/BC_LC_test-018.jpg",
"images/BCLC/BC_LC_test-019.jpg",
"images/BCLC/BC_LC_test-020.jpg",
"images/BCLC/BC_LC_test-021.jpg",
"images/BCLC/BC_LC_test-022.jpg",
"images/BCLC/BC_LC_test-023.jpg",
"images/BCLC/BC_LC_test-024.jpg",
"images/BCLC/BC_LC_test-025.jpg",
"images/BCLC/BC_LC_test-026.jpg",
"images/BCLC/BC_LC_test-027.jpg",
"images/BCLC/BC_LC_test-028.jpg",
"images/BCLC/BC_LC_test-029.jpg",
"images/BCLC/BC_LC_test-030.jpg",
"images/BCLC/BC_LC_test-031.jpg",
"images/BCLC/BC_LC_test-032.jpg",
"images/BCLC/BC_LC_test-033.jpg",
"images/BCLC/BC_LC_test-034.jpg",
"images/BCLC/BC_LC_test-035.jpg",
"images/BCLC/BC_LC_test-036.jpg",
"images/BCLC/BC_LC_test-037.jpg",
"images/BCLC/BC_LC_test-038.jpg",
"images/BCLC/BC_LC_test-039.jpg",
"images/BCLC/BC_LC_test-041.jpg",
"images/BCLC/BC_LC_test-042.jpg",
"images/BCLC/BC_LC_test-043.jpg",
"images/BCLC/BC_LC_test-044.jpg",
"images/BCLC/BC_LC_test-045.jpg",
"images/BCLC/BC_LC_test-046.jpg",
"images/BCLC/BC_LC_test-047.jpg",
"images/BCLC/BC_LC_test-048.jpg",
"images/BCLC/BC_LC_test-049.jpg",
"images/BCLC/BC_LC_test-050.jpg",
"images/BCLC/BC_LC_test-051.jpg",
"images/BCLC/BC_LC_test-052.jpg",
"images/BCLC/BC_LC_test-053.jpg",
"images/BCLC/BC_LC_test-054.jpg",
"images/BCLC/BC_LC_test-055.jpg",
"images/BCLC/BC_LC_test-056.jpg",
"images/BCLC/BC_LC_test-057.jpg",
"images/BCLC/BC_LC_test-058.jpg",
"images/BCLC/BC_LC_test-059.jpg",
"images/BCLC/BC_LC_test-060.jpg",
"images/BCLC/BC_LC_test-061.jpg",
"images/BCLC/BC_LC_test-062.jpg",
"images/BCLC/BC_LC_test-063.jpg",
"images/BCLC/BC_LC_test-064.jpg",
"images/BCLC/BC_LC_test-065.jpg",
"images/BCLC/BC_LC_test-066.jpg",
"images/BCLC/BC_LC_test-067.jpg",
"images/BCLC/BC_LC_test-068.jpg",
"images/BCLC/BC_LC_test-069.jpg",
"images/BCLC/BC_LC_test-070.jpg",
"images/BCLC/BC_LC_test-071.jpg",
"images/BCLC/BC_LC_test-072.jpg",
"images/BCLC/BC_LC_test-073.jpg",
"images/BCLC/BC_LC_test-074.jpg",
"images/BCLC/BC_LC_test-075.jpg",
"images/BCLC/BC_LC_test-076.jpg",
"images/BCLC/BC_LC_test-077.jpg",
"images/BCLC/BC_LC_test-078.jpg",
"images/BCLC/BC_LC_test-079.jpg",
"images/BCLC/BC_LC_test-080.jpg",
"images/BCLC/BC_LC_test-081.jpg",
"images/BCLC/BC_LC_test-082.jpg",
"images/BCLC/BC_LC_test-083.jpg",
"images/BCLC/BC_LC_test-084.jpg",
"images/BCLC/BC_LC_test-085.jpg",
"images/BCLC/BC_LC_test-086.jpg",
"images/BCLC/BC_LC_test-087.jpg",
"images/BCLC/BC_LC_test-088.jpg",
"images/BCLC/BC_LC_test-089.jpg",
"images/BCLC/BC_LC_test-090.jpg",
"images/BCLC/BC_LC_test-091.jpg",
"images/BCLC/BC_LC_test-092.jpg",
"images/BCLC/BC_LC_test-093.jpg",
"images/BCLC/BC_LC_test-094.jpg",
"images/BCLC/BC_LC_test-095.jpg",
"images/BCLC/BC_LC_test-096.jpg",
"images/BCLC/BC_LC_test-097.jpg",
"images/BCLC/BC_LC_test-098.jpg",
"images/BCLC/BC_LC_test-099.jpg",
"images/BCLC/BC_LC_test-100.jpg",
"images/BCLC/BC_LC_test-101.jpg",
"images/BCLC/BC_LC_test-102.jpg",
"images/BCLC/BC_LC_test-103.jpg",
"images/BCLC/BC_LC_test-104.jpg",
"images/BCLC/BC_LC_test-106.jpg",
"images/BCLC/BC_LC_test-107.jpg",
"images/BCLC/BC_LC_test-108.jpg",
"images/BCLC/BC_LC_test-109.jpg",
"images/BCLC/BC_LC_test-110.jpg",
"images/BCLC/BC_LC_test-111.jpg",
"images/BCLC/BC_LC_test-112.jpg",
"images/BCLC/BC_LC_test-113.jpg",
"images/BCLC/BC_LC_test-114.jpg",
"images/BCLC/BC_LC_test-115.jpg",
"images/BCLC/BC_LC_test-116.jpg",
"images/BCLC/BC_LC_test-117.jpg",
"images/BCLC/BC_LC_test-118.jpg",
"images/BCLC/BC_LC_test-119.jpg",
"images/BCLC/BC_LC_test-120.jpg",
"images/BCLC/BC_LC_test-121.jpg",
"images/BCLC/BC_LC_test-122.jpg",
"images/BCLC/BC_LC_test-123.jpg",
"images/BCLC/BC_LC_test-124.jpg",
"images/BCLC/BC_LC_test-125.jpg",
"images/BCLC/BC_LC_test-126.jpg",
"images/BCLC/BC_LC_test-127.jpg",
"images/BCLC/BC_LC_test-128.jpg",
"images/BCLC/BC_LC_test-130.jpg",
"images/BCLC/BC_LC_test-131.jpg",
"images/BCLC/BC_LC_test-132.jpg",
"images/BCLC/BC_LC_test-133.jpg",
"images/BCLC/BC_LC_test-135.jpg",
"images/BCLC/BC_LC_test-136.jpg",
"images/BCLC/BC_LC_test-137.jpg",
"images/BCLC/BC_LC_test-138.jpg",
"images/BCLC/BC_LC_test-139.jpg",
"images/BCLC/BC_LC_test-140.jpg",
"images/BCLC/BC_LC_test-141.jpg",
"images/BCLC/BC_LC_test-142.jpg",
"images/BCLC/BC_LC_test-143.jpg",
"images/BCLC/BC_LC_test-144.jpg",
"images/BCLC/BC_LC_test-146.jpg",
"images/BCLC/BC_LC_test-147.jpg",
"images/BCLC/BC_LC_test-148.jpg",
"images/BCLC/BC_LC_test-149.jpg",
"images/BCLC/BC_LC_test-150.jpg",
"images/BCLC/BC_LC_test-151.jpg",
"images/BCLC/BC_LC_test-152.jpg",
"images/BCLC/BC_LC_test-153.jpg",
"images/BCLC/BC_LC_test-154.jpg",
"images/BCLC/BC_LC_test-155.jpg",
"images/BCLC/BC_LC_test-156.jpg",
"images/BCLC/BC_LC_test-157.jpg",
"images/BCLC/BC_LC_test-158.jpg",
"images/BCLC/BC_LC_test-160.jpg",
"images/BCLC/BC_LC_test-161.jpg",
"images/BCLC/BC_LC_test-162.jpg",
"images/BCLC/BC_LC_test-163.jpg",
"images/BCLC/BC_LC_test-164.jpg",
"images/BCLC/BC_LC_test-165.jpg",
"images/BCLC/BC_LC_test-166.jpg",
"images/BCLC/BC_LC_test-167.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Midnight Theater",
                "type": "slideshow",
                "icon": "images/mt_card.jpg",
                "imageSequence": [
"images/MT/mt-0001.jpg",
"images/MT/mt-0002.jpg",
"images/MT/mt-0003.jpg",
"images/MT/mt-0004.jpg",
"images/MT/mt-0005.jpg",
"images/MT/mt-0006.jpg",
"images/MT/mt-0007.jpg",
"images/MT/mt-0008.jpg",
"images/MT/mt-0009.jpg",
"images/MT/mt-0010.jpg",
"images/MT/mt-0011.jpg",
"images/MT/mt-0012.jpg",
"images/MT/mt-0013.jpg",
"images/MT/mt-0014.jpg",
"images/MT/mt-0015.jpg",
"images/MT/mt-0016.jpg",
"images/MT/mt-0017.jpg",
"images/MT/mt-0018.jpg",
"images/MT/mt-0019.jpg",
"images/MT/mt-0020.jpg",
"images/MT/mt-0021.jpg",
"images/MT/mt-0022.jpg",
"images/MT/mt-0023.jpg",
"images/MT/mt-0024.jpg",
"images/MT/mt-0025.jpg",
"images/MT/mt-0026.jpg",
"images/MT/mt-0027.jpg",
"images/MT/mt-0028.jpg",
"images/MT/mt-0029.jpg",
"images/MT/mt-0030.jpg",
"images/MT/mt-0031.jpg",
"images/MT/mt-0032.jpg",
"images/MT/mt-0033.jpg",
"images/MT/mt-0034.jpg",
"images/MT/mt-0035.jpg",
"images/MT/mt-0036.jpg",
"images/MT/mt-0037.jpg",
"images/MT/mt-0038.jpg",
"images/MT/mt-0039.jpg",
"images/MT/mt-0040.jpg",
"images/MT/mt-0041.jpg",
"images/MT/mt-0042.jpg",
"images/MT/mt-0043.jpg",
"images/MT/mt-0044.jpg",
"images/MT/mt-0045.jpg",
"images/MT/mt-0046.jpg",
"images/MT/mt-0047.jpg",
"images/MT/mt-0048.jpg",
"images/MT/mt-0049.jpg",
"images/MT/mt-0050.jpg",
"images/MT/mt-0051.jpg",
"images/MT/mt-0052.jpg",
"images/MT/mt-0053.jpg",
"images/MT/mt-0054.jpg",
"images/MT/mt-0055.jpg",
"images/MT/mt-0056.jpg",
"images/MT/mt-0057.jpg",
"images/MT/mt-0058.jpg",
"images/MT/mt-0059.jpg",
"images/MT/mt-0060.jpg",
"images/MT/mt-0061.jpg",
"images/MT/mt-0062.jpg",
"images/MT/mt-0063.jpg",
"images/MT/mt-0064.jpg",
"images/MT/mt-0065.jpg",
"images/MT/mt-0066.jpg",
"images/MT/mt-0067.jpg",
"images/MT/mt-0068.jpg",
"images/MT/mt-0069.jpg",
"images/MT/mt-0070.jpg",
"images/MT/mt-0071.jpg",
"images/MT/mt-0072.jpg",
"images/MT/mt-0073.jpg",
"images/MT/mt-0074.jpg",
"images/MT/mt-0075.jpg",
"images/MT/mt-0076.jpg",
"images/MT/mt-0077.jpg",
"images/MT/mt-0078.jpg",
"images/MT/mt-0079.jpg",
"images/MT/mt-0080.jpg",
"images/MT/mt-0081.jpg",
"images/MT/mt-0082.jpg",
"images/MT/mt-0083.jpg",
"images/MT/mt-0084.jpg",
"images/MT/mt-0085.jpg",
"images/MT/mt-0086.jpg",
"images/MT/mt-0087.jpg",
"images/MT/mt-0088.jpg",
"images/MT/mt-0089.jpg",
"images/MT/mt-0090.jpg",
"images/MT/mt-0091.jpg",
"images/MT/mt-0092.jpg",
"images/MT/mt-0093.jpg",
"images/MT/mt-0094.jpg",
"images/MT/mt-0095.jpg",
"images/MT/mt-0096.jpg",
"images/MT/mt-0097.jpg",
"images/MT/mt-0098.jpg",
"images/MT/mt-0099.jpg",
"images/MT/mt-0100.jpg",
"images/MT/mt-0101.jpg",
"images/MT/mt-0102.jpg",
"images/MT/mt-0103.jpg",
"images/MT/mt-0104.jpg",
"images/MT/mt-0105.jpg",
"images/MT/mt-0106.jpg",
"images/MT/mt-0107.jpg",
"images/MT/mt-0108.jpg",
"images/MT/mt-0109.jpg",
"images/MT/mt-0110.jpg",
"images/MT/mt-0111.jpg",
"images/MT/mt-0112.jpg",
"images/MT/mt-0113.jpg",
"images/MT/mt-0114.jpg",
"images/MT/mt-0115.jpg",
"images/MT/mt-0116.jpg",
"images/MT/mt-0117.jpg",
"images/MT/mt-0118.jpg",
"images/MT/mt-0119.jpg",
"images/MT/mt-0120.jpg",
"images/MT/mt-0121.jpg",
"images/MT/mt-0122.jpg",
"images/MT/mt-0123.jpg",
"images/MT/mt-0124.jpg",
"images/MT/mt-0125.jpg",
"images/MT/mt-0126.jpg",
"images/MT/mt-0127.jpg",
"images/MT/mt-0128.jpg",
"images/MT/mt-0129.jpg",
"images/MT/mt-0130.jpg",
"images/MT/mt-0131.jpg",
"images/MT/mt-0132.jpg",
"images/MT/mt-0133.jpg",
"images/MT/mt-0134.jpg",
"images/MT/mt-0135.jpg",
"images/MT/mt-0136.jpg",
"images/MT/mt-0137.jpg",
"images/MT/mt-0138.jpg",
"images/MT/mt-0139.jpg",
"images/MT/mt-0140.jpg",
"images/MT/mt-0141.jpg",
"images/MT/mt-0142.jpg",
"images/MT/mt-0143.jpg",
"images/MT/mt-0144.jpg",
"images/MT/mt-0145.jpg",
"images/MT/mt-0146.jpg",
"images/MT/mt-0147.jpg",
"images/MT/mt-0148.jpg",
"images/MT/mt-0149.jpg",
"images/MT/mt-0150.jpg",
"images/MT/mt-0151.jpg",
"images/MT/mt-0152.jpg",
"images/MT/mt-0153.jpg",
"images/MT/mt-0154.jpg",
"images/MT/mt-0155.jpg",
"images/MT/mt-0156.jpg",
"images/MT/mt-0157.jpg",
"images/MT/mt-0158.jpg",
"images/MT/mt-0159.jpg",
"images/MT/mt-0160.jpg",
"images/MT/mt-0161.jpg",
"images/MT/mt-0162.jpg",
"images/MT/mt-0163.jpg",
"images/MT/mt-0164.jpg",
"images/MT/mt-0165.jpg",
"images/MT/mt-0166.jpg",
"images/MT/mt-0167.jpg",
"images/MT/mt-0168.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },

        ]
    },
    "comics_link": {
        "title": "comics",
        "projects": [
            {
                "title": "Goblin Universe",
                "type": "in_medias_res",
                "icon": "images/GU_card.jpg",
                "imageSequence": [
					"images/comics/appleOfEvile_01.jpg",
					"images/comics/appleOfEvile_02.jpg",
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Lucy Chapline",
                "type": "in_medias_res",
                "icon": "images/E01_card.jpg",
                "imageSequence": [
					"images/comics/E01_20_ink.jpg",
					"images/comics/E01_22_ink.jpg"

					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Entropy",
                "type": "cover-style",
                "icon": "images/E02_card.jpg",
                "imageSequence": [
					"images/comics/E2_18.jpg",
					"images/comics/E2_19.jpg",
					"images/comics/E2_20.jpg",
					"images/comics/E2_21.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Lost Worlds",
                "type": "cover-style",
                "icon": "images/v_p_card.jpg",
                "imageSequence": [
					"images/comics/v_p14.jpg",
					"images/comics/v_p15.jpg",
					"images/comics/v_p16.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            }
        ]
    }
};