const projectData = {
    "story_link": {
        "title": "storyboards",
        "projects": [
            {
                "title": "Big Cat Little Cat",
                "type": "slideshow",
                "icon": "images/BC_LC_card.jpg",
                "imageSequence": [
"images/BCLC/BC_LC_test-001.jpg",
"images/BCLC/BC_LC_test-002.jpg",
"images/BCLC/BC_LC_test-003.jpg",
"images/BCLC/BC_LC_test-004.jpg",
"images/BCLC/BC_LC_test-005.jpg",
"images/BCLC/BC_LC_test-006.jpg",
"images/BCLC/BC_LC_test-007.jpg",
"images/BCLC/BC_LC_test-008.jpg",
"images/BCLC/BC_LC_test-009.jpg",
"images/BCLC/BC_LC_test-010.jpg",
"images/BCLC/BC_LC_test-011.jpg",
"images/BCLC/BC_LC_test-012.jpg",
"images/BCLC/BC_LC_test-013.jpg",
"images/BCLC/BC_LC_test-016.jpg",
"images/BCLC/BC_LC_test-017.jpg",
"images/BCLC/BC_LC_test-018.jpg",
"images/BCLC/BC_LC_test-019.jpg",
"images/BCLC/BC_LC_test-020.jpg",
"images/BCLC/BC_LC_test-021.jpg",
"images/BCLC/BC_LC_test-022.jpg",
"images/BCLC/BC_LC_test-023.jpg",
"images/BCLC/BC_LC_test-024.jpg",
"images/BCLC/BC_LC_test-025.jpg",
"images/BCLC/BC_LC_test-026.jpg",
"images/BCLC/BC_LC_test-027.jpg",
"images/BCLC/BC_LC_test-028.jpg",
"images/BCLC/BC_LC_test-029.jpg",
"images/BCLC/BC_LC_test-030.jpg",
"images/BCLC/BC_LC_test-031.jpg",
"images/BCLC/BC_LC_test-032.jpg",
"images/BCLC/BC_LC_test-033.jpg",
"images/BCLC/BC_LC_test-034.jpg",
"images/BCLC/BC_LC_test-035.jpg",
"images/BCLC/BC_LC_test-036.jpg",
"images/BCLC/BC_LC_test-037.jpg",
"images/BCLC/BC_LC_test-038.jpg",
"images/BCLC/BC_LC_test-039.jpg",
"images/BCLC/BC_LC_test-041.jpg",
"images/BCLC/BC_LC_test-042.jpg",
"images/BCLC/BC_LC_test-043.jpg",
"images/BCLC/BC_LC_test-044.jpg",
"images/BCLC/BC_LC_test-045.jpg",
"images/BCLC/BC_LC_test-046.jpg",
"images/BCLC/BC_LC_test-047.jpg",
"images/BCLC/BC_LC_test-048.jpg",
"images/BCLC/BC_LC_test-049.jpg",
"images/BCLC/BC_LC_test-050.jpg",
"images/BCLC/BC_LC_test-051.jpg",
"images/BCLC/BC_LC_test-052.jpg",
"images/BCLC/BC_LC_test-053.jpg",
"images/BCLC/BC_LC_test-054.jpg",
"images/BCLC/BC_LC_test-055.jpg",
"images/BCLC/BC_LC_test-056.jpg",
"images/BCLC/BC_LC_test-057.jpg",
"images/BCLC/BC_LC_test-058.jpg",
"images/BCLC/BC_LC_test-059.jpg",
"images/BCLC/BC_LC_test-060.jpg",
"images/BCLC/BC_LC_test-061.jpg",
"images/BCLC/BC_LC_test-062.jpg",
"images/BCLC/BC_LC_test-063.jpg",
"images/BCLC/BC_LC_test-064.jpg",
"images/BCLC/BC_LC_test-065.jpg",
"images/BCLC/BC_LC_test-066.jpg",
"images/BCLC/BC_LC_test-067.jpg",
"images/BCLC/BC_LC_test-068.jpg",
"images/BCLC/BC_LC_test-069.jpg",
"images/BCLC/BC_LC_test-070.jpg",
"images/BCLC/BC_LC_test-071.jpg",
"images/BCLC/BC_LC_test-072.jpg",
"images/BCLC/BC_LC_test-073.jpg",
"images/BCLC/BC_LC_test-074.jpg",
"images/BCLC/BC_LC_test-075.jpg",
"images/BCLC/BC_LC_test-076.jpg",
"images/BCLC/BC_LC_test-077.jpg",
"images/BCLC/BC_LC_test-078.jpg",
"images/BCLC/BC_LC_test-079.jpg",
"images/BCLC/BC_LC_test-080.jpg",
"images/BCLC/BC_LC_test-081.jpg",
"images/BCLC/BC_LC_test-082.jpg",
"images/BCLC/BC_LC_test-083.jpg",
"images/BCLC/BC_LC_test-084.jpg",
"images/BCLC/BC_LC_test-085.jpg",
"images/BCLC/BC_LC_test-086.jpg",
"images/BCLC/BC_LC_test-087.jpg",
"images/BCLC/BC_LC_test-088.jpg",
"images/BCLC/BC_LC_test-089.jpg",
"images/BCLC/BC_LC_test-090.jpg",
"images/BCLC/BC_LC_test-091.jpg",
"images/BCLC/BC_LC_test-092.jpg",
"images/BCLC/BC_LC_test-093.jpg",
"images/BCLC/BC_LC_test-094.jpg",
"images/BCLC/BC_LC_test-095.jpg",
"images/BCLC/BC_LC_test-096.jpg",
"images/BCLC/BC_LC_test-097.jpg",
"images/BCLC/BC_LC_test-098.jpg",
"images/BCLC/BC_LC_test-099.jpg",
"images/BCLC/BC_LC_test-100.jpg",
"images/BCLC/BC_LC_test-101.jpg",
"images/BCLC/BC_LC_test-102.jpg",
"images/BCLC/BC_LC_test-103.jpg",
"images/BCLC/BC_LC_test-104.jpg",
"images/BCLC/BC_LC_test-106.jpg",
"images/BCLC/BC_LC_test-107.jpg",
"images/BCLC/BC_LC_test-108.jpg",
"images/BCLC/BC_LC_test-109.jpg",
"images/BCLC/BC_LC_test-110.jpg",
"images/BCLC/BC_LC_test-111.jpg",
"images/BCLC/BC_LC_test-112.jpg",
"images/BCLC/BC_LC_test-113.jpg",
"images/BCLC/BC_LC_test-114.jpg",
"images/BCLC/BC_LC_test-115.jpg",
"images/BCLC/BC_LC_test-116.jpg",
"images/BCLC/BC_LC_test-117.jpg",
"images/BCLC/BC_LC_test-118.jpg",
"images/BCLC/BC_LC_test-119.jpg",
"images/BCLC/BC_LC_test-120.jpg",
"images/BCLC/BC_LC_test-121.jpg",
"images/BCLC/BC_LC_test-122.jpg",
"images/BCLC/BC_LC_test-123.jpg",
"images/BCLC/BC_LC_test-124.jpg",
"images/BCLC/BC_LC_test-125.jpg",
"images/BCLC/BC_LC_test-126.jpg",
"images/BCLC/BC_LC_test-127.jpg",
"images/BCLC/BC_LC_test-128.jpg",
"images/BCLC/BC_LC_test-130.jpg",
"images/BCLC/BC_LC_test-131.jpg",
"images/BCLC/BC_LC_test-132.jpg",
"images/BCLC/BC_LC_test-133.jpg",
"images/BCLC/BC_LC_test-135.jpg",
"images/BCLC/BC_LC_test-136.jpg",
"images/BCLC/BC_LC_test-137.jpg",
"images/BCLC/BC_LC_test-138.jpg",
"images/BCLC/BC_LC_test-139.jpg",
"images/BCLC/BC_LC_test-140.jpg",
"images/BCLC/BC_LC_test-141.jpg",
"images/BCLC/BC_LC_test-142.jpg",
"images/BCLC/BC_LC_test-143.jpg",
"images/BCLC/BC_LC_test-144.jpg",
"images/BCLC/BC_LC_test-146.jpg",
"images/BCLC/BC_LC_test-147.jpg",
"images/BCLC/BC_LC_test-148.jpg",
"images/BCLC/BC_LC_test-149.jpg",
"images/BCLC/BC_LC_test-150.jpg",
"images/BCLC/BC_LC_test-151.jpg",
"images/BCLC/BC_LC_test-152.jpg",
"images/BCLC/BC_LC_test-153.jpg",
"images/BCLC/BC_LC_test-154.jpg",
"images/BCLC/BC_LC_test-155.jpg",
"images/BCLC/BC_LC_test-156.jpg",
"images/BCLC/BC_LC_test-157.jpg",
"images/BCLC/BC_LC_test-158.jpg",
"images/BCLC/BC_LC_test-160.jpg",
"images/BCLC/BC_LC_test-161.jpg",
"images/BCLC/BC_LC_test-162.jpg",
"images/BCLC/BC_LC_test-163.jpg",
"images/BCLC/BC_LC_test-164.jpg",
"images/BCLC/BC_LC_test-165.jpg",
"images/BCLC/BC_LC_test-166.jpg",
"images/BCLC/BC_LC_test-167.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Midnight Theater",
                "type": "slideshow",
                "icon": "images/mt_card.jpg",
                "imageSequence": [
"images/MT/mt-001.jpg",
"images/MT/mt-002.jpg",
"images/MT/mt-003.jpg",
"images/MT/mt-004.jpg",
"images/MT/mt-005.jpg",
"images/MT/mt-006.jpg",
"images/MT/mt-007.jpg",
"images/MT/mt-008.jpg",
"images/MT/mt-009.jpg",
"images/MT/mt-010.jpg",
"images/MT/mt-011.jpg",
"images/MT/mt-012.jpg",
"images/MT/mt-013.jpg",
"images/MT/mt-014.jpg",
"images/MT/mt-015.jpg",
"images/MT/mt-016.jpg",
"images/MT/mt-017.jpg",
"images/MT/mt-018.jpg",
"images/MT/mt-019.jpg",
"images/MT/mt-020.jpg",
"images/MT/mt-021.jpg",
"images/MT/mt-022.jpg",
"images/MT/mt-023.jpg",
"images/MT/mt-024.jpg",
"images/MT/mt-025.jpg",
"images/MT/mt-026.jpg",
"images/MT/mt-027.jpg",
"images/MT/mt-028.jpg",
"images/MT/mt-029.jpg",
"images/MT/mt-030.jpg",
"images/MT/mt-031.jpg",
"images/MT/mt-032.jpg",
"images/MT/mt-033.jpg",
"images/MT/mt-034.jpg",
"images/MT/mt-035.jpg",
"images/MT/mt-036.jpg",
"images/MT/mt-037.jpg",
"images/MT/mt-038.jpg",
"images/MT/mt-039.jpg",
"images/MT/mt-040.jpg",
"images/MT/mt-041.jpg",
"images/MT/mt-042.jpg",
"images/MT/mt-043.jpg",
"images/MT/mt-044.jpg",
"images/MT/mt-045.jpg",
"images/MT/mt-046.jpg",
"images/MT/mt-047.jpg",
"images/MT/mt-048.jpg",
"images/MT/mt-049.jpg",
"images/MT/mt-050.jpg",
"images/MT/mt-051.jpg",
"images/MT/mt-052.jpg",
"images/MT/mt-053.jpg",
"images/MT/mt-054.jpg",
"images/MT/mt-055.jpg",
"images/MT/mt-056.jpg",
"images/MT/mt-057.jpg",
"images/MT/mt-058.jpg",
"images/MT/mt-059.jpg",
"images/MT/mt-060.jpg",
"images/MT/mt-061.jpg",
"images/MT/mt-062.jpg",
"images/MT/mt-063.jpg",
"images/MT/mt-064.jpg",
"images/MT/mt-065.jpg",
"images/MT/mt-066.jpg",
"images/MT/mt-067.jpg",
"images/MT/mt-068.jpg",
"images/MT/mt-069.jpg",
"images/MT/mt-070.jpg",
"images/MT/mt-071.jpg",
"images/MT/mt-072.jpg",
"images/MT/mt-073.jpg",
"images/MT/mt-074.jpg",
"images/MT/mt-075.jpg",
"images/MT/mt-076.jpg",
"images/MT/mt-077.jpg",
"images/MT/mt-078.jpg",
"images/MT/mt-079.jpg",
"images/MT/mt-080.jpg",
"images/MT/mt-081.jpg",
"images/MT/mt-082.jpg",
"images/MT/mt-083.jpg",
"images/MT/mt-084.jpg",
"images/MT/mt-085.jpg",
"images/MT/mt-086.jpg",
"images/MT/mt-087.jpg",
"images/MT/mt-088.jpg",
"images/MT/mt-089.jpg",
"images/MT/mt-090.jpg",
"images/MT/mt-091.jpg",
"images/MT/mt-092.jpg",
"images/MT/mt-093.jpg",
"images/MT/mt-094.jpg",
"images/MT/mt-095.jpg",
"images/MT/mt-096.jpg",
"images/MT/mt-097.jpg",
"images/MT/mt-098.jpg",
"images/MT/mt-099.jpg",
"images/MT/mt-100.jpg",
"images/MT/mt-101.jpg",
"images/MT/mt-102.jpg",
"images/MT/mt-103.jpg",
"images/MT/mt-104.jpg",
"images/MT/mt-105.jpg",
"images/MT/mt-106.jpg",
"images/MT/mt-107.jpg",
"images/MT/mt-108.jpg",
"images/MT/mt-109.jpg",
"images/MT/mt-110.jpg",
"images/MT/mt-111.jpg",
"images/MT/mt-112.jpg",
"images/MT/mt-113.jpg",
"images/MT/mt-114.jpg",
"images/MT/mt-115.jpg",
"images/MT/mt-116.jpg",
"images/MT/mt-117.jpg",
"images/MT/mt-118.jpg",
"images/MT/mt-119.jpg",
"images/MT/mt-120.jpg",
"images/MT/mt-121.jpg",
"images/MT/mt-122.jpg",
"images/MT/mt-123.jpg",
"images/MT/mt-124.jpg",
"images/MT/mt-125.jpg",
"images/MT/mt-126.jpg",
"images/MT/mt-127.jpg",
"images/MT/mt-128.jpg",
"images/MT/mt-129.jpg",
"images/MT/mt-130.jpg",
"images/MT/mt-131.jpg",
"images/MT/mt-132.jpg",
"images/MT/mt-133.jpg",
"images/MT/mt-134.jpg",
"images/MT/mt-135.jpg",
"images/MT/mt-136.jpg",
"images/MT/mt-137.jpg",
"images/MT/mt-138.jpg",
"images/MT/mt-139.jpg",
"images/MT/mt-140.jpg",
"images/MT/mt-141.jpg",
"images/MT/mt-142.jpg",
"images/MT/mt-143.jpg",
"images/MT/mt-144.jpg",
"images/MT/mt-145.jpg",
"images/MT/mt-146.jpg",
"images/MT/mt-147.jpg",
"images/MT/mt-148.jpg",
"images/MT/mt-149.jpg",
"images/MT/mt-150.jpg",
"images/MT/mt-151.jpg",
"images/MT/mt-152.jpg",
"images/MT/mt-153.jpg",
"images/MT/mt-154.jpg",
"images/MT/mt-155.jpg",
"images/MT/mt-156.jpg",
"images/MT/mt-157.jpg",
"images/MT/mt-158.jpg",
"images/MT/mt-159.jpg",
"images/MT/mt-160.jpg",
"images/MT/mt-161.jpg",
"images/MT/mt-162.jpg",
"images/MT/mt-163.jpg",
"images/MT/mt-164.jpg",
"images/MT/mt-165.jpg",
"images/MT/mt-166.jpg",
"images/MT/mt-167.jpg",
"images/MT/mt-168.jpg",
"images/MT/mt-169.jpg",
"images/MT/mt-170.jpg",
"images/MT/mt-171.jpg",
"images/MT/mt-172.jpg",
"images/MT/mt-173.jpg",
"images/MT/mt-174.jpg",
"images/MT/mt-175.jpg",
"images/MT/mt-176.jpg",
"images/MT/mt-177.jpg",
"images/MT/mt-178.jpg",
"images/MT/mt-179.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Cyber Heist",
                "type": "slideshow",
                "icon": "images/t3.jpg",
                "imageSequence": [
					"images/t3/Timeline 1_0000.jpg",
					"images/t3/Timeline 1_0001.jpg",
					"images/t3/Timeline 1_0002.jpg",
					"images/t3/Timeline 1_0003.jpg",
					"images/t3/Timeline 1_0004.jpg",
					"images/t3/Timeline 1_0005.jpg",
					"images/t3/Timeline 1_0006.jpg",
					"images/t3/Timeline 1_0007.jpg",
					"images/t3/Timeline 1_0008.jpg",
					"images/t3/Timeline 1_0009.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            }
        ]
    },
    "comics_link": {
        "title": "comics",
        "projects": [
            {
                "title": "Goblin Universe",
                "type": "in_medias_res",
                "icon": "images/GU_card.jpg",
                "imageSequence": [
					"images/comics/appleOfEvile_01.jpg",
					"images/comics/appleOfEvile_02.jpg",
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Lucy Chapline",
                "type": "in_medias_res",
                "icon": "images/E01_card.jpg",
                "imageSequence": [
					"images/comics/E01_20_ink.jpg",
					"images/comics/E01_22_ink.jpg"

					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Entropy",
                "type": "cover-style",
                "icon": "images/E02_card.jpg",
                "imageSequence": [
					"images/comics/E2_18.jpg",
					"images/comics/E2_19.jpg",
					"images/comics/E2_20.jpg",
					"images/comics/E2_21.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            },
            {
                "title": "Lost Worlds",
                "type": "cover-style",
                "icon": "images/v_p_card.jpg",
                "imageSequence": [
					"images/comics/v_p14.jpg",
					"images/comics/v_p15.jpg",
					"images/comics/v_p16.jpg"
					],
					"additionalItems": [
						{ "title": "Concept Art", "image": "images/t1.jpg" },
						{ "title": "Behind the Scenes", "image": "images/t2.jpg" }
					]
            }
        ]
    }
};